### ISSUE TITLE
Small C++ riddle

### ISSUE THREAD

**Issue by scunz** [macgitver/libHeaven#17]
Heya @antis81 

I just tried to create a QDebug operator<< for the `Heaven::ViewIdentifier` class. The patch is pretty straight forward as shown below. But actually, the code below took me almost 3 hours to debug. The reason is that the `return stream << qPrintable(s);` line is an endless recursion. It actually screwed up my system so completely that I had to reboot 5 times to even locate where I have to debug at all...

I've found the solution; just thought this would be a nice riddle to solve, if you want. Here's the patch:

``` diff
diff --git a/src/libHeaven/CentralUI/Views/ViewIdentifier.cpp b/src/libHeaven/CentralUI/Views/ViewIdentifier.cpp
index 913036e..e459676 100644
--- a/src/libHeaven/CentralUI/Views/ViewIdentifier.cpp
+++ b/src/libHeaven/CentralUI/Views/ViewIdentifier.cpp
@@ -16,6 +16,8 @@
  *
  */

+#include <QStringBuilder>
+
 #include "libHeaven/CentralUI/Views/ViewIdentifier.hpp"

 namespace Heaven
@@ -221,3 +223,9 @@ namespace Heaven
     }

 }
+
+QDebug& operator<<(QDebug& stream, const Heaven::ViewIdentifier& id)
+{
+    QString s = QLatin1Literal("(VId:") % id.toString() % QChar(L')');
+    return stream << qPrintable(s);
+}
diff --git a/src/libHeaven/CentralUI/Views/ViewIdentifier.hpp b/src/libHeaven/CentralUI/Views/ViewIdentifier.hpp
index 45d39ba..cde8e3b 100644
--- a/src/libHeaven/CentralUI/Views/ViewIdentifier.hpp
+++ b/src/libHeaven/CentralUI/Views/ViewIdentifier.hpp
@@ -60,4 +60,6 @@ namespace Heaven

 }

+HEAVEN_API QDebug& operator<<(QDebug& stream, const Heaven::ViewIdentifier& id);
+
 #endif
```

**Comment by scunz** [comment]
@antis81, did you figure out, why this endless recursion happens? Or should I just explain this curiosity?

**Comment by antis81** [comment]
@scunz To be true, I haven't spent much time coding the last two weeks ... But this one seems logically :smile:. The expression `return stream << qPrintable(s);` calls the operator recursively and adds endlessly the new string variable `s`. Shouldn't it be void anyways?

Explaination would be nice :smile:

**Comment by scunz** [comment]
Almost correct ^^ Actually, the code is 100% ok as it stands. `operator<<` shall return the LHS. Note, that these are the same:

```
a << b << c;
a.operator<<(b.operator<<(c));
```

The first line of the << operator, calculates the result as a QString - and it is actually correct.
The second line turns the QString into a QByteArray (`qPrintable(s)`). The result of that is shifted into the stream. This should call to `QDebug operator<<( QDebug& d, QByteArray s)`. But it doesn' t, which is the problem:

The <<-Operator with a QByteArray as second parameter is not defined (I forgot to include QDebug). Thus the compiler tries its best to resolve this. It first figures out that a <<-Operator taking QDebug and ViewIdentifier is defined. Then it realizes that it can convert a QByteArray into a ViewIdentifer (Because there is a constructor that can do that). So, it converts the Byte Array into a ViewIdentifer and calls itself...
