### ISSUE TITLE
Menu not initializing correctly

### ISSUE THREAD

**Issue by scunz** [macgitver/libHeaven#20]
On Mac OS X 10.8 a stock MGV built with Qt 5.1.1 doesn't show a menu before you activate another app and then go back to MGV.

**Comment by antis81** [comment]
Magically this issue disappeared with my local changes in the branch `mgv-modules -> nf/f/commit-changes`. Don't know what's going on here yet.

Btw. another hint to solve this:
It is not only the menu, but also QSettings not being initialized correctly (pathes, sizes, etc. are always default instead of the saved values).

**Comment by antis81** [comment]
@scunz Looks like your "purified skies" PR fixed this. Can close?

**Comment by scunz** [comment]
Does is? Well, for me it "improves" the problem but doesn't solve it totally.

**Comment by scunz** [comment]
After all, I'm still not sure what exactly causes this to happen. I have found one thing: We shouldn't be giving the `QMenuBar` a parent. So I changed the code to never give `QMenuBar` objects a parent inside `libHeavenActions`.

Before this change: I start mgv, then press CMD + , (for preferences) and as soon as I close the dialog, the menu appears. With this change: I start mgv, then as soon as I press CMD + , the menu appears with the dialog.

However, the reason cannot be that the Menu isn't installed correctly, because the "Quit" and "About" items are correctly "merged" into the Apple-Menu.

So I'd rather like to keep this open until we can really see where we've fucked up :)

**Comment by antis81** [comment]
> Before this change: I start mgv, then press CMD + , (for preferences) and as soon as I close the dialog, the menu appears. With this change: I start mgv, then as soon as I press CMD + , the menu appears with the dialog.

I retried several times including a clean build. I fell over the c++11 stuff :). It should work even on OSX 10.6.8 with clang 3.3 ... but that's another story. For now, I simply outcommented the lines in the `CMakeLists.txt`.

Now I have the same behaviour again as written above: No menu on start, but calling the settings dialog works. Hm, this reminds me of having similar problem with the QFileDialog without a parent. So this is a good thing to look for. I'll try with the `commit-changes` branch in which I simply set a parent to the CommitWidget. I'll report back later :clock1:.

**Comment by antis81** [comment]
Fixed long ago ...

**Comment by scunz** [comment]
I started thinking that this is _really_ a bug somewhere in Qt. Actually, _every_ simple app that I write shows this behaviour on Mac OS X. Maybe something is wrong with my pattern:

``` C++

class MW : public QMainWindow
{
public:
    MW() {
        menuBar()->addMenu("Foo")->addAction("Bar");
        show();
    }
};

int main(int c, char** v) {
    QApplication a(c,v);
    MW m;
    return a.exec();
}
```

Should be okay, shouldn't it?

**Comment by antis81** [comment]
hm, might be you need something like `ui->setupUi(this)`??

**Comment by scunz** [comment]
There is no .ui file :)
