### ISSUE TITLE
ToolButtons are grayed out

### ISSUE THREAD

**Issue by scunz** [macgitver/libHeaven#21]
On Mac OS X, all buttons inside our tool bars are drawn with a disabled-font and style.

**Comment by antis81** [comment]
Since we switched to the new style, this is no more true :smile: :ok:

**Comment by scunz** [comment]
Really? Didn't notice that, actually. But cool if it's `true` :)

**Comment by antis81** [comment]
U online ? Didn't expect. Yeah we're getting closer to the :checkered_flag: we set somewhat unintentionally for V0.1. Could you go online in irc, please? Would like to clear another bigger issue :).
