### ISSUE TITLE
Keyboard Shortcuts for Heaven Actions

### ISSUE THREAD

**Issue by antis81** [macgitver/libHeaven#7]
Should be available :+1:. The current approach with the '&' char seems a little "antiquated" to me though and raises complexity when it comes to translating. What about simply implementing something similar to the `QAction::setShortcut()` and `QAction::setShortcutContext()` methods?

**Comment by scunz** [comment]
Ideally, all QAction properties should be available through hic and `Heaven::Action`.

It's not hard to implement though:
- add getter to `Heaven::Action`
- add setter to `Heaven::Action` and `Heaven::ActionPrivate`
- add validation code for the new properties to `HICProperty::isPropertyAllowed` - shortcut would be TRString or String; while shortcutcontext would probably be String (for now)
- currently, shortcutContext requires special handling in `HIGenSource::writeSetProperties` (must turn the string into a valid enum)
- New keywords should be added to the `addons/hic.xml` file (It's a highlighting script for kate / Qt-Creator)

Even better would be a general enumeration-support in hic. `isPropertyAllowed` would then set shortcutContext to a property value that could sanitize it's values. Then the special handling in `writeSetProperties` could be based upon that informations...

**Comment by antis81** [comment]
Ok, I'll give it a try.

**Comment by antis81** [comment]
Implemented in PR #8
